### ISSUE TITLE
Randomized Random Starting Age sometimes doesn't appear in the Spoiler Log

### ISSUE THREAD

**Issue by fenhl** [fenhl/OoT-Randomizer#23]
Originally reported as https://github.com/OoTRandomizer/OoT-Randomizer/issues/1962:

> I noticed this in some mixed pools seeds and I also generated a relatively normal seed on Fenhl branch that had this issue.
> I don't know if this is a symptom of something more serious.

No version given, will have to check if it still happens on latest.

**Comment by r0bd0g** [comment]
As I said in that issue, it occurred in the mixed pools [tourney seeds] from early last year. So I'm linking the async spreasheet. You can look through those and see how some show randomized starting age and some don't (for example, 04 is the first one to actually show it -- also, all the ones that do say it say they are starting as adult, but that might just be a coincidence). Checking the version of just the first one (it's possible it changed in between some of the batches of seeds) shows 7.1.43 Fenhl-11. And here's a link to another seed where it definitely occurred (it's probably the 'normal' one I generated myself), but the seed has long since expired.
https://docs.google.com/spreadsheets/d/115YjuD1i8PZypPsR2r57N9gg6D_QQsCqUzbal2pfLFA/edit
https://ootrandomizer.com/seed/get?id=1389615

**Comment by mracsys** [comment]
This is still an issue on 7.1.51 Fenhl-1. It almost consistently appears on the latest weekly preset with the following changes:
* Full Child/Adult Spawn randomization
* Full Boss Shuffle
* Full Blue Warp randomization

`randomized_settings` is populated in the spoiler as long as entrance randomization succeeds without exceeding the retry limit.

**Comment by fenhl** [comment]
Closing in favor of OoTRandomizer#1962 since according to OoTRandomizer#2256 the root cause is not specific to this branch. Thanks @mracsys for the analysis!
